# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifishare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='loaction_y',
            new_name='location_y',
        ),
    ]
