# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifishare', '0002_auto_20170909_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='user_connection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='destination',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user_orign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='origin',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
